"""FPGA development board mechanical data.

GENERATED FILE -- do not edit by hand.
Regenerate with::

    uv run --no-project --with ezdxf --with pdfplumber --with cadquery \\
        python fpga/extract.py

Coordinates follow :mod:`tools.schema`: origin at the lower-left corner of the
board, X right, Y up, top view, millimetres.  Each board is drawn the way its
maker draws it:

* the Arty A7 and ULX3S with their Pmod or GPIO edge and USB along the top
* the PYNQ-Z2 with its Pmod hosts on the right
* ButterStick with its USB-C and Ethernet on the right
* the Icepi Zero the way Raspberry Pi draw a Zero, its GPIO header along the
  top and its connector edge at the bottom
* Cynthion with its two Pmod hosts along the bottom
"""

from __future__ import annotations

from tools.schema import BoardSpec, Feature, Hole, Outline, PmodHeader, Source

BOARDS: dict[str, BoardSpec] = {}

#: Feature numbers are fixed across the family: a number means the same part on
#: every sheet.  A board that does not carry the part still gets a row, so a
#: gap in a schedule reads as "not on this board" rather than as an omission.
FEATURE_NUMBERS = {
    1: 'USB programming / console port',
    2: 'Second USB port',
    3: 'Ethernet RJ45',
    4: 'User LEDs, single colour',
    5: 'User LEDs, tri-colour',
    6: 'Expansion connector, first',
    7: 'Expansion connector, second',
    8: 'Expansion connector, third',
    9: 'Third USB port',
    10: 'Fourth USB port',
    11: 'Status LEDs, driven by the debug controller',
}


BOARDS['arty-a7'] = BoardSpec(
    key='arty-a7',
    title='Digilent Arty A7',
    subtitle='A7-35T and A7-100T',
    family="fpga",
    front_edge='top',
    outline=Outline(width=109.0, height=87.0,
                    corner_radius=0.0, thickness=None,
                    edges=(
                        ('line', 0.0, 0.0, 109.0, 0.0),
                        ('line', 109.0, 0.0, 109.0, 87.0),
                        ('line', 109.0, 87.0, 0.0, 87.0),
                        ('line', 0.0, 87.0, 0.0, 0.0),
                    )),
    holes=(

    ),
    pmods=(
        PmodHeader(key='pmod_ja', label='JA', designator='JA', edge='top',
                   cx=20.2, cy=75.25, pin1_x=13.85, pin1_y=74.0,
                   body_x0=12.6, body_y0=73.32, body_x1=27.84, body_y1=86.88),
        PmodHeader(key='pmod_jb', label='JB', designator='JB', edge='top',
                   cx=43.0, cy=75.25, pin1_x=36.65, pin1_y=74.0,
                   body_x0=35.4, body_y0=73.32, body_x1=50.64, body_y1=86.88),
        PmodHeader(key='pmod_jc', label='JC', designator='JC', edge='top',
                   cx=65.8, cy=75.25, pin1_x=59.45, pin1_y=74.0,
                   body_x0=58.2, body_y0=73.32, body_x1=73.44, body_y1=86.88),
        PmodHeader(key='pmod_jd', label='JD', designator='JD', edge='top',
                   cx=88.6, cy=75.25, pin1_x=82.25, pin1_y=74.0,
                   body_x0=81.0, body_y0=73.32, body_x1=96.24, body_y1=86.88),
    ),
    features=(
        Feature(key='usb_prog', label='micro-USB J10, programming and console', kind='usb_power',
                designator='J10', x0=-0.65, y0=61.32, x1=4.56, y1=68.76,
                note="Shell outline from the PDF plot; centre line from the DXF's shell slots.", number=1),
        Feature(key='ethernet', label='Ethernet RJ45 J9', kind='ethernet',
                designator='J9', x0=-0.24, y0=34.56, x1=26.057, y1=53.4,
                note="Body outline from the PDF plot; centre line from the DXF's locating pegs.", number=3),
        Feature(key='leds', label='LEDs LD4-LD7, 4 on 7.00 mm pitch', kind='led',
                designator='LD4-LD7', x0=8.16, y0=9.545, x1=30.84, y1=10.46,
                note='Bodies from the PDF plot; which row is which follows the package size, see notes.', number=4),
        Feature(key='rgb_leds', label='Tri-colour LEDs LD0-LD3, 4 on 7.00 mm pitch', kind='led',
                designator='LD0-LD3', x0=8.16, y0=3.195, x1=30.84, y1=4.803,
                note='Bodies from the PDF plot; which row is which follows the package size, see notes.', number=5),
    ),
    sources=(
        Source(label='Mechanical drawing',
               ref='https://digilent.com/reference/_media/reference/programmable-logic/arty-a7/arty_a7.zip',
               note='Digilent, Arty_A7_DXF.DXF and Mechanical_Arty_A7.pdf, dated 2020-09-02. Outline, pin fields, slots and pegs from the DXF; component bodies from the PDF, whose plot scale is recovered from the outline (axes agree to 0.20 %).'),
        Source(label='3D model',
               ref='https://digilent.com/reference/_media/reference/programmable-logic/arty/arty_revc_cad.zip',
               note="Digilent, Arty Rev C: used only to identify which of the PDF's outlines are the eight user LEDs."),
        Source(label='Reference manual',
               ref='https://digilent.com/reference/programmable-logic/arty-a7/reference-manual',
               note='Pmod JA, JB, JC, JD; four tri-colour and four single LEDs.'),
        Source(label='Mounting',
               ref='https://forum.digilent.com/topic/4523-410-319-mounting/',
               note='Digilent staff, 2017-07-19: "There are no thru holes or mounting provisions"; the board stands on rubber feet.'),
    ),
    notes=(
        'No mounting holes. The drawing shows four 10.0 mm rubber feet centred 5.0 mm from each corner; a plate has to carry the board on those or clamp its edges.',
        "The Pmod pin rows are 2.50 mm apart on the drawing, not 2.54, and the hosts are on a 22.80 mm pitch where the PDF's dimension reads 0.90 in; both within the general tolerance.",
        "JA is nearest the USB and Ethernet corner, per the reference manual's callout figure.",
        'The 1.6 x 1.6 mm LED row nearest the edge is taken as the tri-colour LD0-LD3 and the 0603 row behind it as LD4-LD7; no source names them.',
        'Bodies read from the PDF plot are good to about +/-0.3 mm; the DXF figures carry the general tolerance.',
    ),
    envelope_note='',
)

BOARDS['ulx3s'] = BoardSpec(
    key='ulx3s',
    title='ULX3S',
    subtitle='v3.0.3, v3.0.7, v3.0.8 and v3.1.7',
    family="fpga",
    front_edge='top',
    outline=Outline(width=93.98, height=50.8,
                    corner_radius=0.0, thickness=1.6,
                    edges=(
                        ('line', 0.0, 50.8, 0.0, 0.0),
                        ('line', 93.98, 50.8, 0.0, 50.8),
                        ('line', 93.98, 0.0, 93.98, 50.8),
                        ('line', 0.0, 0.0, 93.98, 0.0),
                    )),
    holes=(
        Hole(x=8.89, y=3.81, dia=3.2, label='H1', kind='mount', keepout_dia=5.5),
        Hole(x=85.09, y=3.81, dia=3.2, label='H2', kind='mount', keepout_dia=5.5),
        Hole(x=85.09, y=46.99, dia=3.2, label='H3', kind='mount', keepout_dia=5.5),
        Hole(x=8.89, y=46.99, dia=3.2, label='H4', kind='mount', keepout_dia=5.5),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='micro-USB US1, FTDI programming and console', kind='usb_power',
                designator='US1', x0=12.78, y0=45.295, x1=22.78, y1=51.895,
                note='', number=1),
        Feature(key='usb_second', label='micro-USB US2, USB host / OTG', kind='connector',
                designator='US2', x0=71.2, y0=45.295, x1=81.2, y1=51.895,
                note='', number=2),
        Feature(key='leds', label='LEDs D0-D7, 8 on 2.54 mm pitch', kind='led',
                designator='D0-D7', x0=7.94, y0=30.941, x1=27.62, y1=34.301,
                note='D0 at the right-hand end.', number=4),
        Feature(key='exp1', label='GPIO header J1, 2x20', kind='header',
                designator='J1', x0=-9.34, y0=-0.52, x1=5.16, y1=51.28,
                note='Right-angle 2x20 socket; pin 1 at (3.81, 49.53). Body overhangs the board edge.', number=6),
        Feature(key='exp2', label='GPIO header J2, 2x20', kind='header',
                designator='J2', x0=88.82, y0=-0.48, x1=103.32, y1=51.32,
                note='Right-angle 2x20 socket; pin 1 at (90.17, 1.27). Body overhangs the board edge.', number=7),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ 300a361b (tag v3.0.3)',
               note='Radiona / emard'),
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ d518b2ce (tag v3.0.7)',
               note='Radiona / emard'),
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ 9908a1f8 (tag v3.0.8)',
               note='Radiona / emard'),
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ cc1817d2 (tag v3.1.7)',
               note='Radiona / emard'),
        Source(label='Board versions',
               ref='https://github.com/emard/ulx3s/blob/master/doc/MANUAL.md',
               note='section "Board Versions": v3.0.3, v3.0.7, v3.0.8 and v3.1.7 are the rows marked "for sale"; the four board files are read and agree on everything drawn here.'),
        Source(label='Board size',
               ref='https://github.com/emard/ulx3s/blob/master/README.md',
               note='quoted: "This is a small (94x51 mm) standalone FPGA board"; the board file gives 93.98 x 50.80, which is 37 x 20 tenths of an inch.'),
    ),
    notes=(
        'Hole IDs are the KiCad reference designators.',
        'No Pmod host. J1 and J2 are right-angle 2x20 sockets on 2.54 mm whose pinout is Pmod compatible, per the maker; pin 1 of each is given in the schedule note.',
        'No Ethernet jack.',
    ),
    envelope_note='',
)

BOARDS['pynq-z2'] = BoardSpec(
    key='pynq-z2',
    title='TUL PYNQ-Z2',
    subtitle='137 x 87 mm',
    family="fpga",
    front_edge='right',
    outline=Outline(width=137.0, height=87.0,
                    corner_radius=0.0, thickness=1.6,
                    edges=(
                        ('line', 0.0, 87.0, 0.0, 0.0),
                        ('line', 137.0, 87.0, 0.0, 87.0),
                        ('line', 137.0, 0.0, 137.0, 87.0),
                        ('line', 0.0, 0.0, 137.0, 0.0),
                    )),
    holes=(
        Hole(x=4.0, y=4.0, dia=3.4, label='MT1', kind='mount', keepout_dia=None),
        Hole(x=133.0, y=4.0, dia=3.4, label='MT2', kind='mount', keepout_dia=None),
        Hole(x=4.0, y=83.0, dia=3.4, label='MT3', kind='mount', keepout_dia=None),
        Hole(x=133.0, y=83.0, dia=3.4, label='MT4', kind='mount', keepout_dia=None),
    ),
    pmods=(
        PmodHeader(key='pmod_a', label='Pmod A', designator='JA', edge='right',
                   cx=126.713, cy=41.101, pin1_x=125.443, pin1_y=47.451,
                   body_x0=129.743, body_y0=33.281, body_x1=138.243, body_y1=49.021),
        PmodHeader(key='pmod_b', label='Pmod B', designator='JB', edge='right',
                   cx=126.713, cy=16.717, pin1_x=125.443, pin1_y=23.067,
                   body_x0=129.743, body_y0=8.897, body_x1=138.243, body_y1=24.637),
    ),
    features=(
        Feature(key='usb_prog', label='micro-USB, programming and console', kind='usb_power',
                designator='', x0=-0.511, y0=29.147, x1=4.489, y1=37.147,
                note='Model part "Micro USB", every solid of it.', number=1),
        Feature(key='usb_second', label='USB type A host port', kind='usb_a',
                designator='', x0=33.017, y0=73.7, x1=50.417, y1=87.4,
                note='Model part "USB-A-20", every solid of it.', number=2),
        Feature(key='ethernet', label='Ethernet RJ45', kind='ethernet',
                designator='', x0=-0.6, y0=40.203, x1=21.055, y1=59.977,
                note='Model part "RT7-174A-XXXX-10PIN", every solid of it.', number=3),
    ),
    sources=(
        Source(label='3D model',
               ref='https://discuss.pynq.io/t/pynq-z2-pcb-3d-step-files/2645',
               note="PYNQ_Z2_20220218.STEP, TUL's SolidWorks export of 2022-02-18 posted by Xilinx; the earlier model on the same thread has the Pmod spacing wrong and is not used."),
        Source(label='User manual',
               ref='https://dpoauwgwqsy2x.cloudfront.net/Download/PYNQ_Z2_User_Manual_v1.1.pdf',
               note='v1.1: Pmod A is the upper host (section 16); 4 LEDs and 2 tri-colour LEDs (section 14).'),
    ),
    notes=(
        'Every dimension is read from the STEP model; TUL publish no drawing. Hole IDs are assigned by this drawing.',
        'The user LEDs LD0-LD3 and the two tri-colour LEDs are not in the model, so schedule rows 4 and 5 are empty; the board has them, above the four push buttons near the lower edge.',
        "TUL's product sheet gives the board as 87 x 140 mm; the model's laminate is 137.0 wide and the Pmod hosts reach 1.2 beyond it.",
    ),
    envelope_note='',
)

BOARDS['butterstick'] = BoardSpec(
    key='butterstick',
    title='ButterStick',
    subtitle='r1.0',
    family="fpga",
    front_edge='right',
    outline=Outline(width=80.0, height=49.0,
                    corner_radius=3.0, thickness=1.6,
                    edges=(
                        ('line', 77.0, 0.0, 3.0, 0.0),
                        ('line', 3.0, 49.0, 77.0, 49.0),
                        ('line', 0.0, 3.0, 0.0, 46.0),
                        ('line', 80.0, 46.0, 80.0, 3.0),
                        ('arc', 0.0, 46.0, 3.0, 49.0, 3.0, 0, 0),
                        ('arc', 80.0, 3.0, 77.0, 0.0, 3.0, 0, 0),
                        ('arc', 3.0, 0.0, 0.0, 3.0, 3.0, 0, 0),
                        ('arc', 77.0, 49.0, 80.0, 46.0, 3.0, 0, 0),
                    )),
    holes=(
        Hole(x=76.0, y=45.0, dia=3.2, label='H1', kind='mount', keepout_dia=6.4),
        Hole(x=76.0, y=4.0, dia=3.2, label='H2', kind='mount', keepout_dia=6.4),
        Hole(x=5.0, y=7.5, dia=3.2, label='SA1', kind='aux', keepout_dia=5.2),
        Hole(x=5.0, y=41.5, dia=3.2, label='SA2', kind='aux', keepout_dia=5.2),
        Hole(x=18.5, y=44.0, dia=3.2, label='SB1', kind='aux', keepout_dia=5.2),
        Hole(x=52.5, y=44.0, dia=3.2, label='SB2', kind='aux', keepout_dia=5.2),
        Hole(x=18.09, y=5.0, dia=3.2, label='SC1', kind='aux', keepout_dia=5.2),
        Hole(x=55.91, y=5.0, dia=3.2, label='SC2', kind='aux', keepout_dia=5.2),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='USB-C J1, programming and console', kind='usb_power',
                designator='J1', x0=72.58, y0=29.68, x1=82.0, y1=40.32,
                note='Courtyard, including the shell overhang past the board edge.', number=1),
        Feature(key='ethernet', label='Ethernet RJ45 CON1', kind='ethernet',
                designator='CON1', x0=62.81, y0=8.065, x1=77.92, y1=26.315,
                note='Pad extent; the footprint carries no body outline.', number=3),
        Feature(key='rgb_leds', label='RGB LEDs D1-D7, 7 on 2.00 mm pitch', kind='led',
                designator='D1-D7', x0=58.4, y0=44.4, x1=71.6, y1=45.6,
                note='D1 at the left-hand end; silkscreen numbers them 0 to 6.', number=5),
        Feature(key='exp1', label='SYZYGY port A, J3', kind='connector',
                designator='J3', x0=0.0, y0=2.0, x1=12.0, y1=47.0,
                note='Fab-layer body outline.', number=6),
        Feature(key='exp2', label='SYZYGY port B, J4', kind='connector',
                designator='J4', x0=13.0, y0=37.0, x1=58.0, y1=49.0,
                note='Fab-layer body outline.', number=7),
        Feature(key='exp3', label='SYZYGY port C, J5', kind='connector',
                designator='J5', x0=12.0, y0=0.0, x1=62.0, y1=12.0,
                note='Fab-layer body outline.', number=8),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/butterstick-fpga/butterstick-hardware  hardware/ButterStick_r1.0/ButterStick.kicad_pcb @ fac6a834',
               note='title block: ButterStick rev r1.0a, dated 2021-01-10; Greg Davill / GsD'),
        Source(label='Board size',
               ref='https://github.com/butterstick-fpga/butterstick-hardware/blob/main/README.md',
               note='quoted: "Board dimensions: 80mm x 49mm"'),
        Source(label='Thickness',
               ref='https://github.com/butterstick-fpga/butterstick-hardware/blob/main/hardware/ButterStick_r1.0/Production/ButterStick-r1.0a-fab-notes.txt',
               note='quoted: "Finished board thickness is 1.6 mm."'),
    ),
    notes=(
        "Hole IDs H1 and H2 are the KiCad reference designators; SA1 to SC2 are the SYZYGY standoff holes of ports A, B and C, plated, and the maker's acrylic plate bolts through all eight.",
        'No Pmod host: expansion is three SYZYGY ports.',
    ),
    envelope_note='',
)

BOARDS['icepi-zero'] = BoardSpec(
    key='icepi-zero',
    title='Icepi Zero',
    subtitle='v1.3, Raspberry Pi Zero form factor',
    family="fpga",
    front_edge='bottom',
    outline=Outline(width=65.0, height=30.0,
                    corner_radius=3.5, thickness=1.6458,
                    edges=(
                        ('line', 65.0, 26.5, 65.0, 3.5),
                        ('line', 0.0, 3.5, 0.0, 26.5),
                        ('line', 61.5, 0.0, 3.5, 0.0),
                        ('line', 3.5, 30.0, 61.5, 30.0),
                        ('arc', 0.0, 26.5, 3.5, 30.0, 3.5, 0, 0),
                        ('arc', 61.5, 30.0, 65.0, 26.5, 3.5, 0, 0),
                        ('arc', 3.5, 0.0, 0.0, 3.5, 3.5, 0, 0),
                        ('arc', 65.0, 3.5, 61.5, 0.0, 3.5, 0, 0),
                    )),
    holes=(
        Hole(x=3.5, y=3.5, dia=2.7, label='H3', kind='mount', keepout_dia=None),
        Hole(x=61.5, y=3.5, dia=2.7, label='H4', kind='mount', keepout_dia=None),
        Hole(x=3.5, y=26.5, dia=2.7, label='H1', kind='mount', keepout_dia=None),
        Hole(x=61.5, y=26.5, dia=2.7, label='H2', kind='mount', keepout_dia=None),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='USB-C J3, JTAG and console', kind='usb_power',
                designator='J3', x0=22.68, y0=-1.93, x1=33.32, y1=7.01,
                note='Courtyard, including the shell overhang past the board edge. The receptacle wired to the on-board FT231X.', number=1),
        Feature(key='usb_second', label='USB-C J5 and J4, to the FPGA, 2 on 12.50 mm pitch', kind='connector',
                designator='J5, J4', x0=35.18, y0=-1.93, x1=58.32, y1=7.01,
                note='Courtyards, shell overhang included; two separate receptacles with 1.86 mm of board between them.', number=2),
        Feature(key='leds', label='User LEDs LED0-LED4, 5 on 2.98 mm pitch', kind='led',
                designator='D1, D4, D2, D3, D5', x0=48.938, y0=7.01, x1=63.83, y1=8.49,
                note='LED0 at the left-hand end. Courtyards of the 0603 bodies.', number=4),
        Feature(key='exp1', label='GPIO header J1, 2x20, not fitted', kind='header',
                designator='J1', x0=6.595, y0=23.455, x1=58.405, y1=29.545,
                note='Courtyard of the unfitted 2x20 position.', number=6),
        Feature(key='exp2', label='GPDI video connector J2', kind='connector',
                designator='J2', x0=6.8, y0=-0.85, x1=18.0, y1=6.65,
                note='Courtyard; the body overhangs the board edge.', number=7),
        Feature(key='exp3', label='microSD card socket J6', kind='connector',
                designator='J6', x0=-0.03, y0=11.45, x1=11.57, y1=23.45,
                note='Courtyard. A card in the socket stands proud of the left edge; the source gives no figure for it.', number=8),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/cheyao/icepi-zero  hardware/v1.3/icepi-zero.kicad_pcb @ 6e4aaba2 (tag v1.3)',
               note='title block: Icepi Zero rev v1.3, dated 2025-07-22; Chengyin Yao (cheyao). Solderpad Hardware Licence 2.1.'),
        Source(label='Board revision',
               ref='https://github.com/cheyao/icepi-zero/releases/tag/v1.3',
               note='the v1.3 tag, "Final mass production files": the revision made in quantity and sold. The same board file later in its history, at d67bb758, is read too and agrees on every position drawn here.'),
        Source(label='Board size',
               ref='https://github.com/cheyao/icepi-zero/blob/v1.3/README.md',
               note='quoted at this tag: "Icepi Zero is an FPGA development board in the popular Raspberry Pi Zero form factor"; the board file gives 65.00 x 30.00 mm.'),
        Source(label='Assembly',
               ref='https://github.com/cheyao/icepi-zero/blob/v1.3/hardware/v1.3/production/bom.csv',
               note='the production bill of materials at the same tag lists no 2x20 header: the GPIO position is not fitted.'),
        Source(label='Form factor compared',
               ref='https://datasheets.raspberrypi.com/rpizero/raspberry-pi-zero-mechanical-drawing.pdf',
               note='Raspberry Pi Zero, RPI-ZERO-V1_2 of 2015-09-23: 65 x 30 mm, corner radius 3.0, 4x M2.5 mounting holes drilled to 2.75 +/-0.05, 58 x 23 apart and 3.5 in from each edge.'),
    ),
    notes=(
        'Hole IDs are the KiCad reference designators.',
        "The mounting holes are the Raspberry Pi Zero pattern: 58.00 x 23.00 mm, 3.50 mm in from each edge of a 65 x 30 board. They are drilled 2.70, the bottom of the Pi Zero drawing's 2.75 +/-0.05 band; the corners are R3.50 where the Pi Zero's are R3.00.",
        'No Pmod host and no Ethernet jack.',
        "The unfitted GPIO position is a Raspberry Pi 40-pin header: 1.00 mm holes on a 2.54 mm grid, with the Pi's 5 V, 3V3 and first GPIO pins in the Pi's places and pin 1 at (8.38, 25.23), in the row farther from the board edge.",
        'The two user buttons are on the underside, centred at (46.40, 15.45) and (46.40, 18.85); a plate under the board has to clear them.',
        'The board file has been re-annotated since the mass-production release. Nothing drawn here moved, but at d67bb758 the programming port is J5 and the user LEDs run D1 to D5 left to right; the designators here are the ones the sold boards were fabbed with.',
    ),
    envelope_note='',
)

BOARDS['cynthion'] = BoardSpec(
    key='cynthion',
    title='Cynthion',
    subtitle='r1.4.0',
    family="fpga",
    front_edge='bottom',
    outline=Outline(width=56.0, height=56.0,
                    corner_radius=3.0, thickness=1.5584,
                    edges=(
                        ('line', 3.0, 0.0, 53.0, 0.0),
                        ('line', 39.0, 56.0, 3.0, 56.0),
                        ('line', 41.0, 55.0, 39.0, 56.0),
                        ('line', 47.0, 55.0, 41.0, 55.0),
                        ('line', 0.0, 53.0, 0.0, 3.0),
                        ('line', 53.0, 56.0, 49.0, 56.0),
                        ('line', 56.0, 3.0, 56.0, 53.0),
                        ('line', 49.0, 56.0, 47.0, 55.0),
                        ('arc', 56.0, 3.0, 53.0, 0.0, 3.0, 0, 0),
                        ('arc', 3.0, 0.0, 0.0, 3.0, 3.0, 0, 0),
                        ('arc', 0.0, 53.0, 3.0, 56.0, 3.0, 0, 0),
                        ('arc', 53.0, 56.0, 56.0, 53.0, 3.0, 0, 0),
                    )),
    holes=(
        Hole(x=3.0, y=3.0, dia=2.2, label='H1', kind='mount', keepout_dia=4.4),
        Hole(x=3.0, y=53.0, dia=2.2, label='H2', kind='mount', keepout_dia=4.4),
        Hole(x=53.0, y=53.0, dia=2.2, label='H3', kind='mount', keepout_dia=4.4),
        Hole(x=53.0, y=3.0, dia=2.2, label='H4', kind='mount', keepout_dia=4.4),
    ),
    pmods=(
        PmodHeader(key='pmod_a', label='Pmod A', designator='J7', edge='bottom',
                   cx=16.57, cy=3.23, pin1_x=22.92, pin1_y=4.5,
                   body_x0=8.95, body_y0=-8.07, body_x1=24.19, body_y1=4.5),
        PmodHeader(key='pmod_b', label='Pmod B', designator='J8', edge='bottom',
                   cx=39.43, cy=3.23, pin1_x=45.78, pin1_y=4.5,
                   body_x0=31.81, body_y0=-8.07, body_x1=47.05, body_y1=4.5),
    ),
    features=(
        Feature(key='usb_prog', label='USB-C J2, CONTROL port', kind='usb_power',
                designator='J2', x0=-1.0, y0=31.53, x1=6.3, y1=40.47,
                note='Fab-layer body outline, shell included.', number=1),
        Feature(key='usb_second', label='USB-C J1, AUX port', kind='connector',
                designator='J1', x0=-1.0, y0=6.53, x1=6.3, y1=15.47,
                note='Fab-layer body outline, shell included.', number=2),
        Feature(key='leds', label='User LEDs D2-D7, 6 on 3.00 mm pitch', kind='led',
                designator='D2-D7', x0=9.77, y0=6.52, x1=26.23, y1=9.48,
                note='D2 at the left-hand end; the FPGA drives them.', number=4),
        Feature(key='exp1', label='Mezzanine receptacle J5, 30-way', kind='connector',
                designator='J5', x0=18.05, y0=11.1, x1=28.55, y1=16.1,
                note='Fab-layer body outline. Board-to-board receptacle on the component side, footprint cynthion:Amphenol_10132798-03.', number=6),
        Feature(key='usb_third', label='USB-C J4, TARGET C port', kind='connector',
                designator='J4', x0=49.7, y0=6.53, x1=57.0, y1=15.47,
                note='Fab-layer body outline, shell included.', number=9),
        Feature(key='usb_fourth', label='USB-A J3, TARGET A port', kind='usb_a',
                designator='J3', x0=45.515, y0=28.7, x1=56.875, y1=43.3,
                note='Fab-layer body outline, shell included.', number=10),
        Feature(key='status_leds', label='Status LEDs D10-D14, 5 on 3.00 mm pitch', kind='led',
                designator='D10-D14', x0=5.27, y0=42.02, x1=18.73, y1=44.98,
                note='D10 at the left-hand end; the debug controller drives them.', number=11),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/greatscottgadgets/cynthion-hardware  cynthion.kicad_pcb @ 13aa71c2 (tag r1.4.0)',
               note="title block: Cynthion rev 1.4.0, Copyright 2019-2024 Great Scott Gadgets, resolved from the project file's text variables at the same commit; Great Scott Gadgets."),
        Source(label='Revision sold',
               ref='https://github.com/greatscottgadgets/cynthion-hardware/releases/tag/r1.4.0',
               note='the r1.4.0 release notes read "Initial production release."; it is the newest release and the tip of the repository, and no commit since has touched the board file.'),
        Source(label='Licence',
               ref='https://github.com/greatscottgadgets/cynthion-hardware/blob/r1.4.0/LICENSE',
               note='CERN Open Hardware Licence Version 2 - Permissive, Copyright (c) 2019-2024 Great Scott Gadgets.'),
        Source(label='Ports and indicators',
               ref='https://cynthion.readthedocs.io/en/latest/hardware/device_overview.html',
               note='names the four USB ports CONTROL, AUX, TARGET C and TARGET A, in that order; six user LEDs driven by the FPGA and five status LEDs driven by the debug microcontroller.'),
    ),
    notes=(
        'Every dimension is read from the board file; Great Scott Gadgets publish no mechanical drawing. Hole IDs are the KiCad reference designators.',
        'Schedule numbers 9, 10 and 11 were added to the family for this board. 1 to 8 mean what they mean on the other FPGA sheets, so the four USB ports read 1, 2, 9, 10.',
        'No Ethernet jack.',
        'Feature 6, J5, is a surface-mount mezzanine receptacle on the component side: a board-to-board expansion socket well inside the outline, not an edge port like the expansion connectors on the other sheets.',
        'Pmod A and B are right-angle sockets: the pin field is on the board and the housing hangs off the front edge, so a peripheral plugs in level with the board rather than standing up from it. The housings reach 8.07 mm past the edge.',
        "The board ships inside an enclosure. The outline drawn is the bare PCB's; the repository publishes no case dimensions.",
        'Buttons PROGRAM and USER on the left edge and RESET on the right are not drawn. They are side-actuated tactile switches whose bodies reach 2.50 mm past the left edge and 2.50 mm past the right.',
    ),
    envelope_note='Assembled envelope, connector overhang and the Pmod housings included: 58.00 x 64.07 mm. With the three side buttons as well it is 61.00 x 64.07 mm, which is what a case has to clear.',
)
