"""FPGA development board mechanical data.

GENERATED FILE -- do not edit by hand.
Regenerate with::

    uv run --no-project --with ezdxf --with pdfplumber --with cadquery \\
        python fpga/extract.py

Coordinates follow :mod:`tools.schema`: origin at the lower-left corner of the
board, X right, Y up, top view, millimetres.  Each board is drawn the way its
maker draws it: the Arty A7 and ULX3S with their Pmod or GPIO edge and USB
along the top, the PYNQ-Z2 with its Pmod hosts on the right, ButterStick with
its USB-C and Ethernet on the right, the Icepi Zero the way Raspberry Pi
draw a Zero, its GPIO header along the top and its connector edge at the
bottom, and Cynthion with its two Pmod hosts along the bottom.
"""

from __future__ import annotations

from tools.schema import BoardSpec, Feature, Hole, Outline, PmodHeader, Source

BOARDS: dict[str, BoardSpec] = {}

#: Feature numbers are fixed across the family: a number means the same part on
#: every sheet.  A board that does not carry the part still gets a row, so a
#: gap in a schedule reads as "not on this board" rather than as an omission.
FEATURE_NUMBERS = {
    1: 'USB programming / console port',
    2: 'Second USB port',
    3: 'Ethernet RJ45',
    4: 'User LEDs, single colour',
    5: 'User LEDs, tri-colour',
    6: 'Expansion connector, first',
    7: 'Expansion connector, second',
    8: 'Expansion connector, third',
    9: 'Third USB port',
    10: 'Fourth USB port',
    11: 'Status LEDs, debug controller',
}


BOARDS['arty-a7'] = BoardSpec(
    key='arty-a7',
    title='Digilent Arty A7',
    subtitle='A7-35T and A7-100T',
    family="fpga",
    front_edge='top',
    outline=Outline(width=109.0, height=87.0,
                    corner_radius=0.0, thickness=None,
                    profile_note='',
                    edges=(
                        ('line', 0.0, 0.0, 109.0, 0.0),
                        ('line', 109.0, 0.0, 109.0, 87.0),
                        ('line', 109.0, 87.0, 0.0, 87.0),
                        ('line', 0.0, 87.0, 0.0, 0.0),
                    )),
    holes=(

    ),
    pmods=(
        PmodHeader(key='pmod_ja', label='JA', designator='JA', edge='top',
                   cx=20.2, cy=75.25, pin1_x=13.85, pin1_y=74.0,
                   body_x0=12.6, body_y0=73.32, body_x1=27.84, body_y1=86.88),
        PmodHeader(key='pmod_jb', label='JB', designator='JB', edge='top',
                   cx=43.0, cy=75.25, pin1_x=36.65, pin1_y=74.0,
                   body_x0=35.4, body_y0=73.32, body_x1=50.64, body_y1=86.88),
        PmodHeader(key='pmod_jc', label='JC', designator='JC', edge='top',
                   cx=65.8, cy=75.25, pin1_x=59.45, pin1_y=74.0,
                   body_x0=58.2, body_y0=73.32, body_x1=73.44, body_y1=86.88),
        PmodHeader(key='pmod_jd', label='JD', designator='JD', edge='top',
                   cx=88.6, cy=75.25, pin1_x=82.25, pin1_y=74.0,
                   body_x0=81.0, body_y0=73.32, body_x1=96.24, body_y1=86.88),
    ),
    features=(
        Feature(key='usb_prog', label='micro-USB J10, programming and console', kind='usb_power',
                designator='J10', x0=-0.65, y0=61.32, x1=4.56, y1=68.76,
                note="Shell outline from the PDF plot; centre line from the DXF's shell slots.", number=1),
        Feature(key='ethernet', label='Ethernet RJ45 J9', kind='ethernet',
                designator='J9', x0=-0.24, y0=34.56, x1=26.057, y1=53.4,
                note="Body outline from the PDF plot; centre line from the DXF's locating pegs.", number=3),
        Feature(key='leds', label='LEDs LD4-LD7, 4 on 7.00 mm pitch', kind='led',
                designator='LD4-LD7', x0=8.16, y0=9.545, x1=30.84, y1=10.46,
                note='Bodies from the PDF plot; which row is which follows the package size, see notes.', number=4),
        Feature(key='rgb_leds', label='Tri-colour LEDs LD0-LD3, 4 on 7.00 mm pitch', kind='led',
                designator='LD0-LD3', x0=8.16, y0=3.195, x1=30.84, y1=4.803,
                note='Bodies from the PDF plot; which row is which follows the package size, see notes.', number=5),
    ),
    sources=(
        Source(label='Mechanical drawing',
               ref='https://digilent.com/reference/_media/reference/programmable-logic/arty-a7/arty_a7.zip',
               note='Digilent, Arty_A7_DXF.DXF and Mechanical_Arty_A7.pdf, dated 2020-09-02. Outline, pin fields, slots and pegs from the DXF; component bodies from the PDF, whose plot scale is recovered from the outline (axes agree to 0.20 %).'),
        Source(label='3D model',
               ref='https://digilent.com/reference/_media/reference/programmable-logic/arty/arty_revc_cad.zip',
               note="Digilent, Arty Rev C: used only to identify which of the PDF's outlines are the eight user LEDs."),
        Source(label='Reference manual',
               ref='https://digilent.com/reference/programmable-logic/arty-a7/reference-manual',
               note='Pmod JA, JB, JC, JD; four tri-colour and four single LEDs.'),
        Source(label='Mounting',
               ref='https://forum.digilent.com/topic/4523-410-319-mounting/',
               note='Digilent staff, 2017-07-19: "There are no thru holes or mounting provisions"; the board stands on rubber feet.'),
    ),
    notes=(
        'No mounting holes. The drawing shows four 10.0 mm rubber feet centred 5.0 mm from each corner; a plate has to carry the board on those or clamp its edges.',
        "The Pmod pin rows are 2.50 mm apart on the drawing, not 2.54, and the hosts are on a 22.80 mm pitch where the PDF's dimension reads 0.90 in; both within the general tolerance.",
        "JA is nearest the USB and Ethernet corner, per the reference manual's callout figure.",
        'The 1.6 x 1.6 mm LED row nearest the edge is taken as the tri-colour LD0-LD3 and the 0603 row behind it as LD4-LD7; no source names them.',
        'Bodies read from the PDF plot are good to about +/-0.3 mm; the DXF figures carry the general tolerance.',
    ),
    envelope_note='',
)

BOARDS['ulx3s'] = BoardSpec(
    key='ulx3s',
    title='ULX3S',
    subtitle='v3.0.3, v3.0.7, v3.0.8 and v3.1.7',
    family="fpga",
    front_edge='top',
    outline=Outline(width=93.98, height=50.8,
                    corner_radius=0.0, thickness=1.6,
                    profile_note='',
                    edges=(
                        ('line', 0.0, 50.8, 0.0, 0.0),
                        ('line', 93.98, 50.8, 0.0, 50.8),
                        ('line', 93.98, 0.0, 93.98, 50.8),
                        ('line', 0.0, 0.0, 93.98, 0.0),
                    )),
    holes=(
        Hole(x=8.89, y=3.81, dia=3.2, label='H1', kind='mount', keepout_dia=5.5),
        Hole(x=85.09, y=3.81, dia=3.2, label='H2', kind='mount', keepout_dia=5.5),
        Hole(x=85.09, y=46.99, dia=3.2, label='H3', kind='mount', keepout_dia=5.5),
        Hole(x=8.89, y=46.99, dia=3.2, label='H4', kind='mount', keepout_dia=5.5),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='micro-USB US1, FTDI programming and console', kind='usb_power',
                designator='US1', x0=12.78, y0=45.295, x1=22.78, y1=51.895,
                note='', number=1),
        Feature(key='usb_second', label='micro-USB US2, USB host / OTG', kind='connector',
                designator='US2', x0=71.2, y0=45.295, x1=81.2, y1=51.895,
                note='', number=2),
        Feature(key='leds', label='LEDs D0-D7, 8 on 2.54 mm pitch', kind='led',
                designator='D0-D7', x0=7.94, y0=30.941, x1=27.62, y1=34.301,
                note='D0 at the right-hand end.', number=4),
        Feature(key='exp1', label='GPIO header J1, 2x20', kind='header',
                designator='J1', x0=-9.34, y0=-0.52, x1=5.16, y1=51.28,
                note='Right-angle 2x20 socket; pin 1 at (3.81, 49.53). Body overhangs the board edge.', number=6),
        Feature(key='exp2', label='GPIO header J2, 2x20', kind='header',
                designator='J2', x0=88.82, y0=-0.48, x1=103.32, y1=51.32,
                note='Right-angle 2x20 socket; pin 1 at (90.17, 1.27). Body overhangs the board edge.', number=7),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ 300a361b (tag v3.0.3)',
               note='Radiona / emard'),
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ d518b2ce (tag v3.0.7)',
               note='Radiona / emard'),
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ 9908a1f8 (tag v3.0.8)',
               note='Radiona / emard'),
        Source(label='KiCad board file',
               ref='https://github.com/emard/ulx3s  ulx3s.kicad_pcb @ cc1817d2 (tag v3.1.7)',
               note='Radiona / emard'),
        Source(label='Board versions',
               ref='https://github.com/emard/ulx3s/blob/master/doc/MANUAL.md',
               note='section "Board Versions": v3.0.3, v3.0.7, v3.0.8 and v3.1.7 are the rows marked "for sale"; the four board files are read and agree on everything drawn here.'),
        Source(label='Board size',
               ref='https://github.com/emard/ulx3s/blob/master/README.md',
               note='quoted: "This is a small (94x51 mm) standalone FPGA board"; the board file gives 93.98 x 50.80, which is 37 x 20 tenths of an inch.'),
    ),
    notes=(
        'Hole IDs are the KiCad reference designators.',
        'No Pmod host. J1 and J2 are right-angle 2x20 sockets on 2.54 mm whose pinout is Pmod compatible, per the maker; pin 1 of each is given in the schedule note.',
        'No Ethernet jack.',
    ),
    envelope_note='',
)

BOARDS['pynq-z2'] = BoardSpec(
    key='pynq-z2',
    title='TUL PYNQ-Z2',
    subtitle='137 x 87 mm',
    family="fpga",
    front_edge='right',
    outline=Outline(width=137.0, height=87.0,
                    corner_radius=0.0, thickness=1.6,
                    profile_note='',
                    edges=(
                        ('line', 0.0, 87.0, 0.0, 0.0),
                        ('line', 137.0, 87.0, 0.0, 87.0),
                        ('line', 137.0, 0.0, 137.0, 87.0),
                        ('line', 0.0, 0.0, 137.0, 0.0),
                    )),
    holes=(
        Hole(x=4.0, y=4.0, dia=3.4, label='MT1', kind='mount', keepout_dia=None),
        Hole(x=133.0, y=4.0, dia=3.4, label='MT2', kind='mount', keepout_dia=None),
        Hole(x=4.0, y=83.0, dia=3.4, label='MT3', kind='mount', keepout_dia=None),
        Hole(x=133.0, y=83.0, dia=3.4, label='MT4', kind='mount', keepout_dia=None),
    ),
    pmods=(
        PmodHeader(key='pmod_a', label='Pmod A', designator='JA', edge='right',
                   cx=126.713, cy=41.101, pin1_x=125.443, pin1_y=47.451,
                   body_x0=129.743, body_y0=33.281, body_x1=138.243, body_y1=49.021),
        PmodHeader(key='pmod_b', label='Pmod B', designator='JB', edge='right',
                   cx=126.713, cy=16.717, pin1_x=125.443, pin1_y=23.067,
                   body_x0=129.743, body_y0=8.897, body_x1=138.243, body_y1=24.637),
    ),
    features=(
        Feature(key='usb_prog', label='micro-USB, programming and console', kind='usb_power',
                designator='', x0=-0.511, y0=29.147, x1=4.489, y1=37.147,
                note='Model part "Micro USB", every solid of it.', number=1),
        Feature(key='usb_second', label='USB type A host port', kind='usb_a',
                designator='', x0=33.017, y0=73.7, x1=50.417, y1=87.4,
                note='Model part "USB-A-20", every solid of it.', number=2),
        Feature(key='ethernet', label='Ethernet RJ45', kind='ethernet',
                designator='', x0=-0.6, y0=40.203, x1=21.055, y1=59.977,
                note='Model part "RT7-174A-XXXX-10PIN", every solid of it.', number=3),
    ),
    sources=(
        Source(label='3D model',
               ref='https://discuss.pynq.io/t/pynq-z2-pcb-3d-step-files/2645',
               note="PYNQ_Z2_20220218.STEP, TUL's SolidWorks export of 2022-02-18 posted by Xilinx; the earlier model on the same thread has the Pmod spacing wrong and is not used."),
        Source(label='User manual',
               ref='https://dpoauwgwqsy2x.cloudfront.net/Download/PYNQ_Z2_User_Manual_v1.1.pdf',
               note='v1.1: Pmod A is the upper host (section 16); 4 LEDs and 2 tri-colour LEDs (section 14).'),
    ),
    notes=(
        'Every dimension is read from the STEP model; TUL publish no drawing. Hole IDs are assigned by this drawing.',
        'The user LEDs LD0-LD3 and the two tri-colour LEDs are not in the model, so schedule rows 4 and 5 are empty; the board has them, above the four push buttons near the lower edge.',
        "TUL's product sheet gives the board as 87 x 140 mm; the model's laminate is 137.0 wide and the Pmod hosts reach 1.2 beyond it.",
    ),
    envelope_note='',
)

BOARDS['butterstick'] = BoardSpec(
    key='butterstick',
    title='ButterStick',
    subtitle='r1.0',
    family="fpga",
    front_edge='right',
    outline=Outline(width=80.0, height=49.0,
                    corner_radius=3.0, thickness=1.6,
                    profile_note='',
                    edges=(
                        ('line', 77.0, 0.0, 3.0, 0.0),
                        ('line', 3.0, 49.0, 77.0, 49.0),
                        ('line', 0.0, 3.0, 0.0, 46.0),
                        ('line', 80.0, 46.0, 80.0, 3.0),
                        ('arc', 0.0, 46.0, 3.0, 49.0, 3.0, 0, 0),
                        ('arc', 80.0, 3.0, 77.0, 0.0, 3.0, 0, 0),
                        ('arc', 3.0, 0.0, 0.0, 3.0, 3.0, 0, 0),
                        ('arc', 77.0, 49.0, 80.0, 46.0, 3.0, 0, 0),
                    )),
    holes=(
        Hole(x=76.0, y=45.0, dia=3.2, label='H1', kind='mount', keepout_dia=6.4),
        Hole(x=76.0, y=4.0, dia=3.2, label='H2', kind='mount', keepout_dia=6.4),
        Hole(x=5.0, y=7.5, dia=3.2, label='SA1', kind='aux', keepout_dia=5.2),
        Hole(x=5.0, y=41.5, dia=3.2, label='SA2', kind='aux', keepout_dia=5.2),
        Hole(x=18.5, y=44.0, dia=3.2, label='SB1', kind='aux', keepout_dia=5.2),
        Hole(x=52.5, y=44.0, dia=3.2, label='SB2', kind='aux', keepout_dia=5.2),
        Hole(x=18.09, y=5.0, dia=3.2, label='SC1', kind='aux', keepout_dia=5.2),
        Hole(x=55.91, y=5.0, dia=3.2, label='SC2', kind='aux', keepout_dia=5.2),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='USB-C J1, programming and console', kind='usb_power',
                designator='J1', x0=72.58, y0=29.68, x1=82.0, y1=40.32,
                note='Courtyard, including the shell overhang past the board edge.', number=1),
        Feature(key='ethernet', label='Ethernet RJ45 CON1', kind='ethernet',
                designator='CON1', x0=62.81, y0=8.065, x1=77.92, y1=26.315,
                note='Pad extent; the footprint carries no body outline.', number=3),
        Feature(key='rgb_leds', label='RGB LEDs D1-D7, 7 on 2.00 mm pitch', kind='led',
                designator='D1-D7', x0=58.4, y0=44.4, x1=71.6, y1=45.6,
                note='D1 at the left-hand end; silkscreen numbers them 0 to 6.', number=5),
        Feature(key='exp1', label='SYZYGY port A, J3', kind='connector',
                designator='J3', x0=0.0, y0=2.0, x1=12.0, y1=47.0,
                note='Fab-layer body outline.', number=6),
        Feature(key='exp2', label='SYZYGY port B, J4', kind='connector',
                designator='J4', x0=13.0, y0=37.0, x1=58.0, y1=49.0,
                note='Fab-layer body outline.', number=7),
        Feature(key='exp3', label='SYZYGY port C, J5', kind='connector',
                designator='J5', x0=12.0, y0=0.0, x1=62.0, y1=12.0,
                note='Fab-layer body outline.', number=8),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/butterstick-fpga/butterstick-hardware  hardware/ButterStick_r1.0/ButterStick.kicad_pcb @ fac6a834',
               note='title block: ButterStick rev r1.0a, dated 2021-01-10; Greg Davill / GsD'),
        Source(label='Board size',
               ref='https://github.com/butterstick-fpga/butterstick-hardware/blob/main/README.md',
               note='quoted: "Board dimensions: 80mm x 49mm"'),
        Source(label='Thickness',
               ref='https://github.com/butterstick-fpga/butterstick-hardware/blob/main/hardware/ButterStick_r1.0/Production/ButterStick-r1.0a-fab-notes.txt',
               note='quoted: "Finished board thickness is 1.6 mm."'),
    ),
    notes=(
        "Hole IDs H1 and H2 are the KiCad reference designators; SA1 to SC2 are the SYZYGY standoff holes of ports A, B and C, plated, and the maker's acrylic plate bolts through all eight.",
        'No Pmod host: expansion is three SYZYGY ports.',
    ),
    envelope_note='',
)

BOARDS['icepi-zero'] = BoardSpec(
    key='icepi-zero',
    title='Icepi Zero',
    subtitle='v1.3, Raspberry Pi Zero form factor',
    family="fpga",
    front_edge='bottom',
    outline=Outline(width=65.0, height=30.0,
                    corner_radius=3.5, thickness=1.6458,
                    profile_note='',
                    edges=(
                        ('line', 65.0, 26.5, 65.0, 3.5),
                        ('line', 0.0, 3.5, 0.0, 26.5),
                        ('line', 61.5, 0.0, 3.5, 0.0),
                        ('line', 3.5, 30.0, 61.5, 30.0),
                        ('arc', 0.0, 26.5, 3.5, 30.0, 3.5, 0, 0),
                        ('arc', 61.5, 30.0, 65.0, 26.5, 3.5, 0, 0),
                        ('arc', 3.5, 0.0, 0.0, 3.5, 3.5, 0, 0),
                        ('arc', 65.0, 3.5, 61.5, 0.0, 3.5, 0, 0),
                    )),
    holes=(
        Hole(x=3.5, y=3.5, dia=2.7, label='H3', kind='mount', keepout_dia=None),
        Hole(x=61.5, y=3.5, dia=2.7, label='H4', kind='mount', keepout_dia=None),
        Hole(x=3.5, y=26.5, dia=2.7, label='H1', kind='mount', keepout_dia=None),
        Hole(x=61.5, y=26.5, dia=2.7, label='H2', kind='mount', keepout_dia=None),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='USB-C J3, JTAG and console', kind='usb_power',
                designator='J3', x0=22.68, y0=-1.93, x1=33.32, y1=7.01,
                note='Courtyard, including the shell overhang past the board edge. The receptacle wired to the on-board FT231X.', number=1),
        Feature(key='usb_second', label='USB-C J5 and J4, to the FPGA, 2 on 12.50 mm pitch', kind='connector',
                designator='J5, J4', x0=35.18, y0=-1.93, x1=58.32, y1=7.01,
                note='Courtyards, shell overhang included; two separate receptacles with 1.86 mm of board between them.', number=2),
        Feature(key='leds', label='User LEDs LED0-LED4, 5 on 2.98 mm pitch', kind='led',
                designator='D1, D4, D2, D3, D5', x0=48.938, y0=7.01, x1=63.83, y1=8.49,
                note='LED0 at the left-hand end. Courtyards of the 0603 bodies.', number=4),
        Feature(key='exp1', label='GPIO header J1, 2x20, not fitted', kind='header',
                designator='J1', x0=6.595, y0=23.455, x1=58.405, y1=29.545,
                note='Courtyard of the unfitted 2x20 position.', number=6),
        Feature(key='exp2', label='GPDI video connector J2', kind='connector',
                designator='J2', x0=6.8, y0=-0.85, x1=18.0, y1=6.65,
                note='Courtyard; the body overhangs the board edge.', number=7),
        Feature(key='exp3', label='microSD card socket J6', kind='connector',
                designator='J6', x0=-0.03, y0=11.45, x1=11.57, y1=23.45,
                note='Courtyard. A card in the socket stands proud of the left edge; the source gives no figure for it.', number=8),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/cheyao/icepi-zero  hardware/v1.3/icepi-zero.kicad_pcb @ 6e4aaba2 (tag v1.3)',
               note='title block: Icepi Zero rev v1.3, dated 2025-07-22; Chengyin Yao (cheyao). Solderpad Hardware Licence 2.1.'),
        Source(label='Board revision',
               ref='https://github.com/cheyao/icepi-zero/releases/tag/v1.3',
               note='the v1.3 tag, "Final mass production files": the revision made in quantity and sold. The same board file later in its history, at d67bb758, is read too and agrees on every position drawn here.'),
        Source(label='Board size',
               ref='https://github.com/cheyao/icepi-zero/blob/v1.3/README.md',
               note='quoted at this tag: "Icepi Zero is an FPGA development board in the popular Raspberry Pi Zero form factor"; the board file gives 65.00 x 30.00 mm.'),
        Source(label='Assembly',
               ref='https://github.com/cheyao/icepi-zero/blob/v1.3/hardware/v1.3/production/bom.csv',
               note='the production bill of materials at the same tag lists no 2x20 header: the GPIO position is not fitted.'),
        Source(label='Form factor compared',
               ref='https://datasheets.raspberrypi.com/rpizero/raspberry-pi-zero-mechanical-drawing.pdf',
               note='Raspberry Pi Zero, RPI-ZERO-V1_2 of 2015-09-23: 65 x 30 mm, corner radius 3.0, 4x M2.5 mounting holes drilled to 2.75 +/-0.05, 58 x 23 apart and 3.5 in from each edge.'),
    ),
    notes=(
        'Hole IDs are the KiCad reference designators.',
        "The mounting holes are the Raspberry Pi Zero pattern: 58.00 x 23.00 mm, 3.50 mm in from each edge of a 65 x 30 board. They are drilled 2.70, the bottom of the Pi Zero drawing's 2.75 +/-0.05 band; the corners are R3.50 where the Pi Zero's are R3.00.",
        'No Pmod host and no Ethernet jack.',
        "The unfitted GPIO position is a Raspberry Pi 40-pin header: 1.00 mm holes on a 2.54 mm grid, with the Pi's 5 V, 3V3 and first GPIO pins in the Pi's places and pin 1 at (8.38, 25.23), in the row farther from the board edge.",
        'The two user buttons are on the underside, centred at (46.40, 15.45) and (46.40, 18.85); a plate under the board has to clear them.',
        'The board file has been re-annotated since the mass-production release. Nothing drawn here moved, but at d67bb758 the programming port is J5 and the user LEDs run D1 to D5 left to right; the designators here are the ones the sold boards were fabbed with.',
    ),
    envelope_note='',
)

BOARDS['cynthion'] = BoardSpec(
    key='cynthion',
    title='Cynthion',
    subtitle='r1.4.0',
    family="fpga",
    front_edge='bottom',
    outline=Outline(width=56.0, height=56.0,
                    corner_radius=3.0, thickness=1.5584,
                    profile_note='The top edge carries a recess 1.00 mm deep, flat from x = 41.00 to 47.00, each end ramping 2.00 back to the edge at x = 39.00 and 49.00. The board file gives no purpose for it.',
                    edges=(
                        ('line', 3.0, 0.0, 53.0, 0.0),
                        ('line', 39.0, 56.0, 3.0, 56.0),
                        ('line', 41.0, 55.0, 39.0, 56.0),
                        ('line', 47.0, 55.0, 41.0, 55.0),
                        ('line', 0.0, 53.0, 0.0, 3.0),
                        ('line', 53.0, 56.0, 49.0, 56.0),
                        ('line', 56.0, 3.0, 56.0, 53.0),
                        ('line', 49.0, 56.0, 47.0, 55.0),
                        ('arc', 56.0, 3.0, 53.0, 0.0, 3.0, 0, 0),
                        ('arc', 3.0, 0.0, 0.0, 3.0, 3.0, 0, 0),
                        ('arc', 0.0, 53.0, 3.0, 56.0, 3.0, 0, 0),
                        ('arc', 53.0, 56.0, 56.0, 53.0, 3.0, 0, 0),
                    )),
    holes=(
        Hole(x=3.0, y=3.0, dia=2.2, label='H1', kind='mount', keepout_dia=4.4),
        Hole(x=3.0, y=53.0, dia=2.2, label='H2', kind='mount', keepout_dia=4.4),
        Hole(x=53.0, y=53.0, dia=2.2, label='H3', kind='mount', keepout_dia=4.4),
        Hole(x=53.0, y=3.0, dia=2.2, label='H4', kind='mount', keepout_dia=4.4),
    ),
    pmods=(
        PmodHeader(key='pmod_a', label='Pmod A', designator='J7', edge='bottom',
                   cx=16.57, cy=3.23, pin1_x=22.92, pin1_y=4.5,
                   body_x0=8.95, body_y0=-8.07, body_x1=24.19, body_y1=4.5),
        PmodHeader(key='pmod_b', label='Pmod B', designator='J8', edge='bottom',
                   cx=39.43, cy=3.23, pin1_x=45.78, pin1_y=4.5,
                   body_x0=31.81, body_y0=-8.07, body_x1=47.05, body_y1=4.5),
    ),
    features=(
        Feature(key='usb_prog', label='USB-C J2, CONTROL port', kind='usb_power',
                designator='J2', x0=-1.0, y0=31.53, x1=6.3, y1=40.47,
                note='Fab-layer body outline, shell included.', number=1),
        Feature(key='usb_second', label='USB-C J1, AUX port', kind='connector',
                designator='J1', x0=-1.0, y0=6.53, x1=6.3, y1=15.47,
                note='Fab-layer body outline, shell included.', number=2),
        Feature(key='leds', label='User LEDs D2-D7, 6 on 3.00 mm pitch', kind='led',
                designator='D2-D7', x0=9.77, y0=6.52, x1=26.23, y1=9.48,
                note='D2 at the left-hand end; the FPGA drives them.', number=4),
        Feature(key='exp1', label='Mezzanine receptacle J5, 30-way', kind='connector',
                designator='J5', x0=18.05, y0=11.1, x1=28.55, y1=16.1,
                note='Fab-layer body outline. Board-to-board receptacle on the component side, footprint cynthion:Amphenol_10132798-03.', number=6),
        Feature(key='usb_third', label='USB-C J4, TARGET C port', kind='connector',
                designator='J4', x0=49.7, y0=6.53, x1=57.0, y1=15.47,
                note='Fab-layer body outline, shell included.', number=9),
        Feature(key='usb_fourth', label='USB-A J3, TARGET A port', kind='usb_a',
                designator='J3', x0=45.515, y0=28.7, x1=56.875, y1=43.3,
                note='Fab-layer body outline, shell included.', number=10),
        Feature(key='status_leds', label='Status LEDs D10-D14, 5 on 3.00 mm pitch', kind='led',
                designator='D10-D14', x0=5.27, y0=42.02, x1=18.73, y1=44.98,
                note='D10 at the left-hand end; the debug controller drives them.', number=11),
    ),
    sources=(
        Source(label='KiCad board file',
               ref='https://github.com/greatscottgadgets/cynthion-hardware  cynthion.kicad_pcb @ 13aa71c2 (tag r1.4.0)',
               note="title block: Cynthion rev 1.4.0, Copyright 2019-2024 Great Scott Gadgets, resolved from the project file's text variables at the same commit; Great Scott Gadgets."),
        Source(label='Revision sold',
               ref='https://github.com/greatscottgadgets/cynthion-hardware/releases/tag/r1.4.0',
               note='the r1.4.0 release notes read "Initial production release."; it is the newest release and the tip of the repository, and no commit since has touched the board file.'),
        Source(label='Licence',
               ref='https://github.com/greatscottgadgets/cynthion-hardware/blob/r1.4.0/LICENSE',
               note='CERN Open Hardware Licence Version 2 - Permissive, Copyright (c) 2019-2024 Great Scott Gadgets.'),
        Source(label='Ports and indicators',
               ref='https://cynthion.readthedocs.io/en/latest/hardware/device_overview.html',
               note='names the four USB ports CONTROL, AUX, TARGET C and TARGET A, in that order; six user LEDs driven by the FPGA and five status LEDs driven by the debug microcontroller.'),
    ),
    notes=(
        'Every dimension is read from the board file; Great Scott Gadgets publish no mechanical drawing. Hole IDs are the KiCad reference designators.',
        'Schedule numbers 9, 10 and 11 were added to the family for this board. 1 to 8 mean what they mean on the other FPGA sheets, so the four USB ports read 1, 2, 9, 10.',
        'No Ethernet jack.',
        'Feature 6, J5, is a surface-mount mezzanine receptacle on the component side: a board-to-board expansion socket well inside the outline, not an edge port like the expansion connectors on the other sheets.',
        'Pmod A and B are right-angle sockets: the pin field is on the board and the housing hangs off the front edge, so a peripheral plugs in level with the board rather than standing up from it. The housings reach 8.07 mm past the edge.',
        "The board ships inside an enclosure. The outline drawn is the bare PCB's; the repository publishes no case dimensions.",
        'Buttons PROGRAM and USER on the left edge and RESET on the right are not drawn. They are side-actuated tactile switches whose bodies reach 2.50 mm past the left edge and 2.50 mm past the right.',
    ),
    envelope_note='Assembled envelope, connector overhang and the Pmod housings included: 58.00 x 64.07 mm. With the three side buttons as well it is 61.00 x 64.07 mm, which is what a case has to clear.',
)

BOARDS['zybo-z7'] = BoardSpec(
    key='zybo-z7',
    title='Digilent Zybo Z7',
    subtitle='Z7-10 and Z7-20',
    family="fpga",
    front_edge='bottom',
    outline=Outline(width=121.92, height=83.82,
                    corner_radius=0.0, thickness=1.571,
                    profile_note='',
                    edges=(
                        ('line', 0.0, 0.0, 121.92, 0.0),
                        ('line', 121.92, 0.0, 121.92, 83.82),
                        ('line', 121.92, 83.82, 0.0, 83.82),
                        ('line', 0.0, 83.82, 0.0, 0.0),
                    )),
    holes=(
        Hole(x=3.81, y=3.81, dia=3.658, label='MT1', kind='mount', keepout_dia=None),
        Hole(x=118.11, y=3.81, dia=3.658, label='MT2', kind='mount', keepout_dia=None),
        Hole(x=3.81, y=80.01, dia=3.658, label='MT3', kind='mount', keepout_dia=None),
        Hole(x=118.11, y=80.01, dia=3.658, label='MT4', kind='mount', keepout_dia=None),
    ),
    pmods=(
        PmodHeader(key='pmod_ja', label='JA', designator='JA', edge='right',
                   cx=113.1, cy=16.6, pin1_x=111.85, pin1_y=22.95,
                   body_x0=110.583, body_y0=8.978, body_x1=115.619, body_y1=24.226),
        PmodHeader(key='pmod_jb', label='JB', designator='JB', edge='bottom',
                   cx=95.5, cy=8.85, pin1_x=101.85, pin1_y=10.1,
                   body_x0=87.886, body_y0=6.335, body_x1=103.104, body_y1=11.381),
        PmodHeader(key='pmod_jc', label='JC', designator='JC', edge='bottom',
                   cx=72.5, cy=8.85, pin1_x=78.85, pin1_y=10.1,
                   body_x0=64.884, body_y0=6.335, body_x1=80.124, body_y1=11.381),
        PmodHeader(key='pmod_jd', label='JD', designator='JD', edge='bottom',
                   cx=49.5, cy=8.85, pin1_x=55.85, pin1_y=10.1,
                   body_x0=41.883, body_y0=6.335, body_x1=57.123, body_y1=11.381),
        PmodHeader(key='pmod_je', label='JE', designator='JE', edge='bottom',
                   cx=26.5, cy=8.85, pin1_x=32.85, pin1_y=10.1,
                   body_x0=18.881, body_y0=6.335, body_x1=34.121, body_y1=11.381),
        PmodHeader(key='pmod_jf', label='JF', designator='JF', edge='left',
                   cx=8.85, cy=36.0, pin1_x=10.1, pin1_y=29.65,
                   body_x0=6.345, body_y0=28.377, body_x1=11.381, body_y1=43.625),
    ),
    features=(
        Feature(key='usb_prog', label='micro-USB J12, programming and console', kind='usb_power',
                designator='J12', x0=-0.501, y0=49.742, x1=5.407, y1=57.737,
                note="Shell outline from the PDF plot; centre line from the DXF's shell pads.", number=1),
        Feature(key='usb_second', label='USB type A host port J11', kind='usb_a',
                designator='J11', x0=0.24, y0=9.437, x1=14.76, y1=24.052,
                note="Body outline from the PDF plot; centre line from the DXF's shield-leg holes.", number=2),
        Feature(key='ethernet', label='Ethernet RJ45 J3', kind='ethernet',
                designator='J3', x0=23.634, y0=62.171, x1=39.375, y1=83.754,
                note="Body outline from the PDF plot; centre line from the DXF's locating pegs.", number=3),
        Feature(key='leds', label='LEDs LD0-LD3, 4 on 7.00 mm pitch', kind='led',
                designator='LD0-LD3', x0=21.65, y0=29.841, x1=44.368, y1=30.758,
                note="Bodies from the PDF plot; which LED is which from the 3D model's designators.", number=4),
        Feature(key='rgb_leds', label='Tri-colour LEDs LD5 and LD6, 2 on 6.50 mm pitch', kind='led',
                designator='LD5, LD6', x0=78.991, y0=29.294, x1=87.101, y1=30.889,
                note="Bodies from the PDF plot; which LED is which from the 3D model's designators.", number=5),
    ),
    sources=(
        Source(label='Mechanical drawing',
               ref='https://digilent.com/reference/_media/reference/programmable-logic/zybo-z7/zybo_z7_dimensions.zip',
               note='Digilent, "Zybo Z7 Mechanical Drawings", dated 2020-09-03. Edge, holes, pin fields, pegs and shell pads from the DXF; bodies from the PDF plot, its scale recovered from the outline per axis (the two agree to 0.20 %).'),
        Source(label='3D model',
               ref='https://files.digilent.com/resources/programmable-logic/zybo-z7/Zybo_Z7.step',
               note="Digilent, Zybo_Z7.step, in the drawing's frame: its solids carry the designators, so they name the plot's outlines. Laminate 1.571 mm."),
        Source(label='Reference manual',
               ref='https://digilent.com/reference/_media/reference/programmable-logic/zybo-z7/zybo-z7_rm.pdf',
               note='Revised 2018-02-21, section 16: JA is the XADC port, JB, JC and JD high-speed, JE standard, JF the MIO port; four user LEDs, and "the Zybo Z7-10 only has one tri-color LED".'),
        Source(label='Schematic',
               ref='https://files.digilent.com/resources/programmable-logic/zybo-z7/zybo-z7-d1-sch.pdf',
               note='Revision D.1: J12 is the micro-USB PROG/UART port, J11 the "USB A" host and J10 a "USB Micro AB" beneath it.'),
        Source(label='Resource Center',
               ref='https://digilent.com/reference/programmable-logic/zybo-z7/start',
               note='Physical, quoted: "Width 3.3 in (88 mm)" and "Length 4.8 in (122 mm)"; the drawing gives 121.92 x 83.82, exactly 4.8 x 3.3 in. Its top view of the board has 3V3 and GND silkscreened at each host\'s end farthest from pin 1.'),
    ),
    notes=(
        "Hole IDs are this drawing's; the DXF names nothing.",
        "Pin rows 2.50 mm apart on the drawing, not 2.54; the host pitch dimensioned below is not the specification's 22.86 (0.90 in).",
        'Drawn fully fitted, as the Zybo Z7-20; the Z7-10 leaves Pmod JB and one tri-colour LED off the same board.',
        'J10, a micro-AB USB socket UNDER J11, projects 2.72 mm below the board and 0.82 past the left edge; C250, under the Ethernet jack, goes deepest at 3.10.',
        "HDMI, audio, Pcam, microSD, the power jack and external JTAG are not marked, so the envelope below counts only what is drawn; the model's, with the audio jacks 1.71 past the right edge, is 124.44 x 83.90.",
        'Bodies read from the PDF plot are good to about +/-0.3 mm.',
    ),
    envelope_note='',
)

BOARDS['ultra96-v2'] = BoardSpec(
    key='ultra96-v2',
    title='Avnet Ultra96-V2',
    subtitle='96Boards CE, 85 x 54 mm',
    family="fpga",
    front_edge='bottom',
    extent_of='PAD EXTENTS',
    outline=Outline(width=85.0, height=54.0,
                    corner_radius=0.0, thickness=None,
                    profile_note='',
                    edges=(
                        ('line', 0.0, 0.0, 85.0, 0.0),
                        ('line', 85.0, 0.0, 85.0, 54.0),
                        ('line', 85.0, 54.0, 0.0, 54.0),
                        ('line', 0.0, 54.0, 0.0, 0.0),
                    )),
    holes=(
        Hole(x=4.0, y=18.5, dia=2.5, label='MT1', kind='mount', keepout_dia=5.0),
        Hole(x=4.0, y=50.0, dia=2.5, label='MT2', kind='mount', keepout_dia=5.0),
        Hole(x=81.013, y=18.5, dia=2.5, label='MT3', kind='mount', keepout_dia=5.0),
        Hole(x=81.013, y=50.0, dia=2.5, label='MT4', kind='mount', keepout_dia=5.0),
    ),
    pmods=(

    ),
    features=(
        Feature(key='usb_prog', label='micro-USB J7, USB 3.0 upstream (device) port', kind='connector',
                designator='J7', x0=35.299, y0=0.635, x1=47.879, y1=4.8,
                note='Pad extent, the ten contacts and the four shield lands; the shell reaches a little beyond them.', number=1),
        Feature(key='usb_second', label='USB 3.0 type A host ports J8 and J9, 2 on 19.40 mm pitch', kind='usb_a',
                designator='J8, J9', x0=48.43, y0=8.175, x1=84.17, y1=13.9,
                note='Pad extent of each, the nine contacts and the two 3.2 mm shell posts.', number=2),
        Feature(key='leds', label='User LEDs D3, D4, D6 and D7, green 0603, 4 off', kind='led',
                designator='D3, D4, D6, D7', x0=63.735, y0=1.286, x1=68.853, y1=3.286,
                note='Pad extent of the four pairs of pads.', number=4),
        Feature(key='exp1', label='96Boards low-speed expansion J5, 40 way, 2x20 on 2.00 mm', kind='header',
                designator='J5', x0=9.5, y0=46.75, x1=48.5, y1=53.25,
                note='Pad extent of the forty pads the plot names.', number=6),
        Feature(key='exp2', label='96Boards high-speed expansion J4, 60 way, 2x30 on 0.80 mm', kind='connector',
                designator='J4', x0=20.9, y0=12.25, x1=44.6, y1=18.65,
                note="Pad extent of the sixty pads the plot names; J4's unnamed hold-down pad is not included.", number=7),
    ),
    sources=(
        Source(label='Mechanical drawing',
               ref='https://github.com/96boards/documentation/blob/master/consumer/ultra96/ultra96-v2/hardware-docs/files/ultra96-v2-mechanical.PDF',
               note='Avnet, ultra96-v2-mechanical.PDF, listed as "Mechanical and Drill": an Altium NEXUS plot of the U96-US1SBC V2 board dated 2019-03-01, republished by Linaro. Everything here is read from its vector content. Its scale is recovered from the outline, per axis (the axes agree to 0.02 %), then checked: the holes land within 13 um of the specification\'s pattern, and the connectors read 2.000 / 0.800 mm across their columns and 5.000 / 4.400 mm between their pad rows.'),
        Source(label='Form factor specification',
               ref='https://github.com/96boards/documentation/blob/master/Specifications/96Boards-CE-Specification.pdf',
               note='Linaro, 96Boards Consumer Edition Low Cost Hardware Platform Specification, cover "Version 1.0, January 2015"; its 2D Reference Drawing is a sheet inside it whose own title block reads 1 FEB 2015. Quoted: "The board without population of connectors shall fit into a 85 x 54mm footprint +/-0.25mm"; "Low speed expansion connector – center line as per mounting holes"; "Keepout for mating shroud 43.00 x 6.50". The hole callout is three stacked rotated annotations, "M2.5", "2.5Ø hole" and "5.0Ø keepout x4", against ordinates 4.00 and 81.00 by 18.50 and 50.00; its 15.45 is unlabelled.'),
        Source(label="Hardware user's guide",
               ref='https://www.avnet.com/wps/wcm/connect/onesite/b85b9556-0b2a-42b3-ad6a-8dcf3eac1ff9/Ultra96-V2-HW-User-Guide-v1_3.pdf',
               note='Avnet, Ultra96-V2 Hardware User\'s Guide v1.3, 02 Jun 2021. Quoted: "Note that there is no on-board, wired Ethernet interface"; "Low Speed Expansion Connector (J5)" and "High Speed Expansion Connector (J4)", which v1.3 corrected. Table 20 names D3, D4, D6, D7 the user LEDs on PS_MIO20 to PS_MIO17 and D9, D10 RADIO_LED0 (yellow) and RADIO_LED1 (blue); 8.2 gives the heat sink screws.'),
        Source(label='Bill of materials',
               ref='https://github.com/96boards/documentation/blob/master/consumer/ultra96/ultra96-v2/hardware-docs/files/ultra96-v2-bom.pdf',
               note='Avnet, ultra96-v2-bom.pdf, which says which designator is which part: J5 "40POS 2MM STR DL SMD", J4 "60POS .8MM VERT DUAL SMD", J7 "MICRO USB 3.0 AB R/A", J8 and J9 "USB 3.0 TYPE A R/A 9PS", D3/D4/D6/D7 green 0603.'),
    ),
    notes=(
        "Hole IDs are assigned by this drawing; Avnet's plot names no hole.",
        'THE FEATURE SCHEDULE GIVES PAD EXTENTS, NOT BODIES. The plot draws no component body outline at all, so each figure is the extent of the pads it names for that part and every connector shell reaches beyond it. Do not cut apertures to them.',
        'Hole diameter is the 96Boards M2.5 figure, not a measurement: the plot draws each hole as a solid 5.0 mm disc, its keepout, and shows no drill.',
        'Expansion pin 1 pad centres: J5 (10.00, 47.50), 20 columns on 2.00 mm; J4 (21.15, 13.25), 30 on 0.80 mm; odd pins on the lower row of each. Pin field centre lines y = 50.00, the mounting hole line, and y = 15.45. Keep 43.00 x 6.50 mm clear around J5 for its mating shroud.',
        'J9 is USB host 1, J8 host 2, per the silkscreen. D3 is user LED 0 at the right-hand end, then D4, D6, D7, 1.40, 1.52 and 1.40 mm apart: not one pitch, so none is quoted.',
        'No Pmod host: the 96Boards connectors take rows 6 and 7, row 8 unused. No Ethernet and no tri-colour LED, so rows 3 and 5 are empty; networking is Wi-Fi, Bluetooth or a mezzanine.',
        "Row 1 is the family's programming and console port; here it is the USB 3.0 device port. Programming is JTAG on header J3, the console header J1; neither is drawn.",
        'Not marked: the mini DisplayPort J6, overhanging the lower edge from x = 20.6 to 29.3; the barrel jack J10 in the upper edge; the microSD socket J2 in the left edge; the radio LEDs D9 and D10.',
        'Normally carried by its heat sink, not the four holes alone: 4x M2.5 x 8 mm through the PCB into the sink, then to a bulkhead with 4x M2.5 (Aavid sink) or 4x #4-40 (bracket and fan).',
    ),
    envelope_note='',
)
