#!/usr/bin/env python3
"""Prove the PDFs committed to this repository are the ones to print.

The PDFs are the useful artefact: a drill template is printed and drilled
through, and a board sheet is printed at 1:1 and laid on the board.  Anyone
who clones this repository gets those files without installing Inkscape, a
font, or `uv`.  That only holds if three things are true of what is actually
committed, and none of them is obvious by looking:

* a PDF is committed beside every sheet, so adding a sheet cannot leave the
  set half-published;
* the committed PDF is a render of the committed SVG, so an SVG change that
  went in without its PDF is caught.  This compares git blobs, not the
  working tree, because the working tree is regenerated by `make diagrams`
  moments earlier and would agree with itself no matter what was committed;
* the page is the size the drawing says it is, and carries no font.  Inkscape
  is asked for text as paths, so a print shop with no DejaVu installed still
  gets the right lettering rather than a substituted face at the wrong width.

PDFs embed a creation timestamp, so the files differ on every rebuild and
cannot be compared byte for byte.  The page content stream can: it is the
drawing itself, and it is reproducible.

Run: uv run --no-project --with pypdf --with pillow python scripts/check_pdfs.py
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from render_svg import to_pdf  # noqa: E402

WORK = ROOT / "tmp" / "check-pdfs"
PT = 25.4 / 72.0

#: Slack on the page size, in millimetres.  A4 is 841.89 points tall, which is
#: 296.9993 mm: the rounding is in the unit, not in the drawing.
SIZE_TOL = 0.01

SIZE_RE = re.compile(r'width="([\d.]+)mm" height="([\d.]+)mm"')


def tracked_sheets() -> list[str]:
    """Every committed SVG under diagrams/, at any depth.

    Listed once.  git's pathspec globs match across directory separators, so
    asking for "diagrams/*.svg" and "diagrams/*/*.svg" returns the same set
    twice and reports every sheet, and every problem, two times over.
    """
    out = subprocess.run(["git", "ls-files", "diagrams"], cwd=ROOT,
                         capture_output=True, text=True, check=True)
    return sorted(p for p in out.stdout.split() if p.endswith(".svg"))


def blob(path: str) -> bytes | None:
    """The committed bytes of *path*, or None if it is not committed."""
    out = subprocess.run(["git", "show", f"HEAD:{path}"], cwd=ROOT,
                         capture_output=True)
    return out.stdout if out.returncode == 0 else None


def content(pdf: Path | bytes) -> bytes:
    source = pdf
    if isinstance(pdf, bytes):
        source = WORK / "_committed.pdf"
        source.write_bytes(pdf)
    return PdfReader(str(source)).pages[0].get_contents().get_data()


def check(svg_path: str) -> list[str]:
    bad: list[str] = []
    pdf_path = svg_path[:-4] + ".pdf"

    svg_bytes = blob(svg_path)
    pdf_bytes = blob(pdf_path)
    if pdf_bytes is None:
        return [f"no {Path(pdf_path).name} committed beside the sheet"]

    scratch = WORK / Path(svg_path).name
    scratch.write_bytes(svg_bytes)
    fresh = to_pdf(scratch)

    if content(pdf_bytes) != content(fresh):
        bad.append("the committed PDF is not a render of the committed SVG; "
                   "run make diagrams and commit both")

    page = PdfReader(str(WORK / "_committed.pdf")).pages[0]
    w = float(page.mediabox.width) * PT
    h = float(page.mediabox.height) * PT
    m = SIZE_RE.search(svg_bytes.decode())
    want_w, want_h = float(m.group(1)), float(m.group(2))
    if abs(w - want_w) > SIZE_TOL or abs(h - want_h) > SIZE_TOL:
        bad.append(f"page is {w:.3f} x {h:.3f} mm, but the drawing is "
                   f"{want_w} x {want_h} mm, so it will not print 1:1")

    fonts = (page.get("/Resources") or {}).get("/Font") or {}
    if fonts:
        bad.append(f"{len(fonts)} embedded font(s); text should be paths so "
                   "the lettering does not depend on the printer's fonts")
    return bad


def main() -> int:
    svgs = tracked_sheets()
    if not svgs:
        raise SystemExit("no sheets committed under diagrams/")
    shutil.rmtree(WORK, ignore_errors=True)
    WORK.mkdir(parents=True)
    total = 0
    try:
        for svg in svgs:
            problems = check(svg)
            total += len(problems)
            name = svg[len("diagrams/"):]
            if problems:
                print(f"{name}: {len(problems)} problem(s)")
                for line in problems:
                    print(f"    {line}")
            else:
                print(f"{name}: PDF committed, matches the SVG, "
                      "true size, no fonts")
    finally:
        shutil.rmtree(WORK, ignore_errors=True)
    print(f"\n{total} problem(s) across {len(svgs)} committed PDFs")
    return 1 if total else 0


if __name__ == "__main__":
    raise SystemExit(main())
