#!/usr/bin/env python3
"""Prove the PDFs committed to this repository are the ones to print.

The PDFs are the useful artefact: a drill template is printed and drilled
through, and a board sheet is printed at 1:1 and laid on the board.  Anyone
who clones this repository gets those files without installing Inkscape, a
font, or `uv`.  That only holds if three things are true of what is actually
committed, and none of them is obvious by looking:

* a PDF is committed beside every sheet, so adding a sheet cannot leave the
  set half-published;
* the PDF is a render of the SVG beside it, so an SVG staged without its PDF
  is caught.  This compares git index blobs, not the working tree, because
  the working tree is regenerated by `make diagrams` moments earlier and
  would agree with itself no matter what the repository holds.  The comparison
  is byte for byte, which it can be because rendering is reproducible -- see
  ``tools/reproducible.py``;
* the page is the size the drawing says it is, and carries no font.  Inkscape
  is asked for text as paths, so a print shop with no DejaVu installed still
  gets the right lettering rather than a substituted face at the wrong width;
* every bound copy really is the committed sheets, page for page, and every
  page carries a bookmark naming the drawing on it.  A bundle is the copy
  people mail and print whole, and it is bound from the sheet PDFs rather
  than re-rendered precisely so that it cannot say something different --
  which is only worth anything if somebody checks.


Run: uv run --no-project --with pypdf --with pillow python tools/check_pdfs.py
"""

from __future__ import annotations

import io
import re
import shutil
import subprocess
import sys
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.layout import FAMILY_DIRS, bundles, drawing_name_for, rel  # noqa: E402
from tools.render_svg import to_pdf  # noqa: E402

WORK = ROOT / "tmp" / "check-pdfs"
PT = 25.4 / 72.0

#: Slack on the page size, in millimetres.  A4 is 841.89 points tall, which is
#: 296.9993 mm: the rounding is in the unit, not in the drawing.
SIZE_TOL = 0.01

SIZE_RE = re.compile(r'width="([\d.]+)mm" height="([\d.]+)mm"')


def tracked_sheets() -> list[str]:
    """Every committed SVG, across every family's output directory.

    The directories come from tools.layout rather than from a glob, so a
    family whose sheets are not committed at all is a missing directory here
    rather than a set that silently comes back empty.
    """
    dirs = [rel(d) for d in FAMILY_DIRS.values()]
    out = subprocess.run(["git", "ls-files", *dirs], cwd=ROOT,
                         capture_output=True, text=True, check=True)
    return sorted(p for p in out.stdout.split() if p.endswith(".svg"))


def blob(path: str) -> bytes | None:
    """The staged bytes of *path*, or None if it is not in the index.

    The index: not the working tree, and not HEAD.  The working tree is
    whatever `make diagrams` wrote moments ago, so it agrees with itself
    whatever the repository holds.  HEAD is the last commit, which would mean
    a rename could not go green until after it had been committed.  The index
    is what is about to become the repository, and staging an SVG without its
    PDF then fails here, before the commit rather than after it.
    """
    out = subprocess.run(["git", "show", f":{path}"], cwd=ROOT,
                         capture_output=True)
    return out.stdout if out.returncode == 0 else None


def check(svg_path: str) -> list[str]:
    bad: list[str] = []
    pdf_path = svg_path[:-4] + ".pdf"

    svg_bytes = blob(svg_path)
    pdf_bytes = blob(pdf_path)
    if pdf_bytes is None:
        return [f"no {Path(pdf_path).name} staged beside the sheet"]

    staged = WORK / "_staged.pdf"
    staged.write_bytes(pdf_bytes)
    scratch = WORK / Path(svg_path).name
    scratch.write_bytes(svg_bytes)
    fresh = to_pdf(scratch)

    # A plain byte comparison, because rendering is reproducible: see
    # tools/reproducible.py.  This used to compare only the page content
    # stream, since cairo stamped a clock into every file it wrote and the
    # bytes therefore never matched.
    if pdf_bytes != fresh.read_bytes():
        bad.append("the staged PDF is not a render of the staged SVG; "
                   "run make diagrams and stage both")

    page = PdfReader(str(staged)).pages[0]
    w = float(page.mediabox.width) * PT
    h = float(page.mediabox.height) * PT
    m = SIZE_RE.search(svg_bytes.decode())
    want_w, want_h = float(m.group(1)), float(m.group(2))
    if abs(w - want_w) > SIZE_TOL or abs(h - want_h) > SIZE_TOL:
        bad.append(f"page is {w:.3f} x {h:.3f} mm, but the drawing is "
                   f"{want_w} x {want_h} mm, so it will not print 1:1")

    fonts = (page.get("/Resources") or {}).get("/Font") or {}
    if fonts:
        bad.append(f"{len(fonts)} embedded font(s); text should be paths so "
                   "the lettering does not depend on the printer's fonts")
    return bad


def content_stream(page) -> bytes:
    """The page's drawing instructions, with the file's furniture left out.

    Empty for a page with no content at all, which is a thing to report and
    never a thing to match on: an empty stream on both sides of a comparison
    is two files agreeing about nothing.  So it is never indexed, and a bundle
    page that yields one is a problem in its own right.
    """
    contents = page.get_contents()
    return contents.get_data() if contents is not None else b""


def check_bundle(path: str, by_stream: dict[bytes, tuple[str, str]]) -> list[str]:
    """One bound copy: the committed sheets, in order, bookmarked by name.

    Page identity is the content stream, which is the drawing itself: the
    surrounding Info dictionary differs between a sheet and a bundle by
    design, since pypdf bound the one and cairo drew the other.  Matching on
    it proves the bundle was assembled from the PDFs in the index rather than
    re-rendered, and it names the sheet each page came from, which is what
    the bookmark is then held to.
    """
    data = blob(path)
    if data is None:
        return ["not staged"]
    reader = PdfReader(io.BytesIO(data))
    bad: list[str] = []
    pages: list[tuple[str, str] | None] = []
    for i, page in enumerate(reader.pages, 1):
        stream = content_stream(page)
        if not stream:
            bad.append(f"page {i} has no content stream to compare")
            pages.append(None)
            continue
        hit = by_stream.get(stream)
        if hit is None:
            bad.append(f"page {i} is not any sheet in the index; it was not "
                       "bound from the committed PDFs")
        pages.append(hit)

    entries = [e for e in (reader.outline or []) if not isinstance(e, list)]
    if len(entries) != len(pages):
        bad.append(f"{len(pages)} page(s) but {len(entries)} bookmark(s); "
                   "every page of a bound copy gets one")
    for entry in entries:
        n = reader.get_destination_page_number(entry)
        hit = pages[n] if 0 <= n < len(pages) else None
        if hit is None:
            continue
        sheet, name = hit
        title = str(entry.title)
        if not title.startswith(f"{name} "):
            bad.append(f"page {n + 1} is {sheet}, so its bookmark should open "
                       f"with the drawing name {name}; it reads {title!r}")
    return bad


def main() -> int:
    svgs = tracked_sheets()
    if not svgs:
        raise SystemExit("no sheets committed under any family's output/")
    shutil.rmtree(WORK, ignore_errors=True)
    WORK.mkdir(parents=True)
    total = 0
    try:
        for svg in svgs:
            problems = check(svg)
            total += len(problems)
            name = svg
            if problems:
                print(f"{name}: {len(problems)} problem(s)")
                for line in problems:
                    print(f"    {line}")
            else:
                print(f"{name}: PDF staged, matches the SVG, "
                      "true size, no fonts")
    finally:
        shutil.rmtree(WORK, ignore_errors=True)
    by_stream: dict[bytes, tuple[str, str]] = {}
    for svg in svgs:
        data = blob(svg[:-4] + ".pdf")
        if data is None:
            continue
        name = drawing_name_for(ROOT / svg)
        for page in PdfReader(io.BytesIO(data)).pages:
            stream = content_stream(page)
            if stream:
                by_stream[stream] = (svg, name)

    bound = [rel(b) for b in bundles()]
    for path in bound:
        problems = check_bundle(path, by_stream)
        total += len(problems)
        if problems:
            print(f"{path}: {len(problems)} problem(s)")
            for line in problems:
                print(f"    {line}")
        else:
            print(f"{path}: bound from the committed sheets, "
                  "bookmarked by drawing name")

    print(f"\n{total} problem(s) across {len(svgs)} PDFs and {len(bound)} "
          "bound copies in the index")
    return 1 if total else 0


if __name__ == "__main__":
    raise SystemExit(main())
